---

#TODO clean /etc/logstash/conf.d/
#sudo rm -f /etc/logstash/conf.d/*
- name: Remove previous configuration
  action: command /bin/rm -Rf /etc/logstash/conf.d/

- name: Create configuration directory
  file: path=/etc/logstash/conf.d/ state=directory

- name: Create Logstash configuration files.
  template:
    src: "{{ item }}.j2"
    dest: "/etc/logstash/conf.d/{{ item }}"
    owner: root
    group: root
    mode: 0644
  with_items:
    - 01-lumberjack-input.conf
    - 10-syslog.conf
    #- 30-lumberjack-elasticsearch-output.conf
  notify: restart logstash

- name: Create Logstash configuration file for local syslog.
  template:
    src: 02-local-syslog-input.conf.j2
    dest: /etc/logstash/conf.d/02-local-syslog-input.conf
    owner: root
    group: root
    mode: 0644
  when: logstash_monitor_local_syslog
  notify: restart logstash

- name: Install collectd
  apt: pkg={{ item }} state=present update_cache=yes
  sudo: yes  
  when: (ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu')
  tags: package
  with_items:
   - collectd
   
- name: Create Logstash configuration file for collectd syslog.
  template:
    src: 02-local-collectd-input.conf.j2
    dest: /etc/logstash/conf.d/02-local-collectd-input.conf
    owner: root
    group: root
    mode: 0644
  when: logstash_monitor_collectd_syslog
  notify: restart logstash

- name: Create Logstash configuration file for jenkins-server syslog.
  template:
    src: 03-local-jenkins-server-input.conf.j2
    dest: /etc/logstash/conf.d/03-local-jenkins-server-input.conf
    owner: root
    group: root
    mode: 0644
  when: logstash_monitor_jenkins_enabled
  notify: restart logstash

- name: Create Logstash configuration file for jenkins syslog.
  template:
    src: 03-local-jenkins-input.conf.j2
    dest: /etc/logstash/conf.d/03-local-jenkins-input.conf
    owner: root
    group: root
    mode: 0644
  when: logstash_monitor_jenkins_enabled
  notify: restart logstash

- name: Create Logstash configuration file for nexus yslog.
  template:
    src: 03-local-nexus-input.conf.j2
    dest: /etc/logstash/conf.d/03-local-nexus-input.conf
    owner: root
    group: root
    mode: 0644
  when: logstash_monitor_nexus_enabled
  notify: restart logstash

- name: Create Logstash configuration file for apache syslog.
  template:
    src: 04-local-apache-input.conf.j2
    dest: /etc/logstash/conf.d/04-local-apache-input.conf
    owner: root
    group: root
    mode: 0644
  when: logstash_monitor_apache_enabled
  notify: restart logstash

- name: Create Logstash configuration file for nginx syslog.
  template:
    src: 04-local-nginx-input.conf.j2
    dest: /etc/logstash/conf.d/04-local-nginx-input.conf
    owner: root
    group: root
    mode: 0644
  when: logstash_monitor_nginx_enabled
  notify: restart logstash

- name: Create Logstash configuration file for tomcat syslog.
  template:
    src: 04-local-tomcat-input.conf.j2
    dest: /etc/logstash/conf.d/04-local-tomcat-input.conf
    owner: root
    group: root
    mode: 0644
  when: logstash_monitor_tomcat_enabled
  notify: restart logstash

- name: Create Logstash configuration file for jetty syslog.
  template:
    src: 04-local-jetty-input.conf.j2
    dest: /etc/logstash/conf.d/04-local-jetty-input.conf
    owner: root
    group: root
    mode: 0644
  when: logstash_monitor_jetty_enabled
  notify: restart logstash

- name: Create Logstash configuration file for sensu syslog.
  template:
    src: 04-local-sensu-input.conf.j2
    dest: /etc/logstash/conf.d/04-local-sensu-input.conf
    owner: root
    group: root
    mode: 0644
  when: logstash_monitor_sensu_enabled
  notify: restart logstash
  
- name: Create Logstash configuration file for jboss syslog.
  template:
    src: 04-local-jboss-input.conf.j2
    dest: /etc/logstash/conf.d/04-local-jboss-input.conf
    owner: root
    group: root
    mode: 0644
  when: logstash_monitor_jboss_enabled
  notify: restart logstash

- name: Create Logstash configuration file for elasticsearch syslog.
  template:
    src: 05-local-elasticsearch-input.conf.j2
    dest: /etc/logstash/conf.d/05-local-elasticsearch-input.conf
    owner: root
    group: root
    mode: 0644
  when: logstash_monitor_elasticsearch_enabled
  notify: restart logstash

- name: Create Logstash configuration file for redis.
  template:
    src: 05-local-redis-input.conf.j2
    dest: /etc/logstash/conf.d/05-local-redis-input.conf
    owner: root
    group: root
    mode: 0644
  when: logstash_monitor_redis_enabled
  notify: restart logstash

- name: Create Logstash configuration file for miscellaneous log.
  template:
    src: 05-local-miscellaneous-input.conf.j2
    dest: /etc/logstash/conf.d/05-local-miscellaneous-input.conf
    owner: root
    group: root
    mode: 0644
  when: logstash_monitor_miscellaneous_enabled
  notify: restart logstash

- name: Create Logstash configuration file for application log.
  template:
    src: 06-local-application-input.conf.j2
    dest: /etc/logstash/conf.d/06-local-application-input.conf
    owner: root
    group: root
    mode: 0644
  when: logstash_monitor_application_enabled
  notify: restart logstash

- name: Create Logstash configuration file for log4j log.
  template:
    src: 07-local-log4j-input.conf.j2
    dest: /etc/logstash/conf.d/07-local-log4j-input.conf
    owner: root
    group: root
    mode: 0644
  when: logstash_monitor_log4j_enabled
  notify: restart logstash

- name: Create Logstash configuration file for sybase log.
  template:
    src: 08-local-sybase-input.conf.j2
    dest: /etc/logstash/conf.d/08-local-sybase-input.conf
    owner: root
    group: root
    mode: 0644
  when: logstash_monitor_sybase_enabled
  notify: restart logstash

#sudo chmod 755 /var/log/upstart
#sudo chmod -R 755 /var/log/*
#sudo chmod 755 /var/log/upstart/*
#sudo chmod 755 /var/log/zabbix/zabbix_agentd.log
#sudo chmod 777 /var/log/upstart/docker.log
#sudo find /var/log/ -type f -name '*\.log' | xargs sudo chmod 755 $1
#TODO
#Add the logstash user to the same group as syslog
#sudo usermod -a -G adm logstash
#sudo apt-get install -y acl
#Set an ACL entry on the relevant logs, like so:
## Single log
#setfacl -m u:logstash:r /var/log/redis/redis-server.log
## Directory of logs
#setfacl -R -m u:logstash:r /var/log/upstart
## Remove ACL entry
#setfacl -x u:logstash /var/log/syslog
## View ACL entries
#getfacl /var/log/syslog
####
#setfacl -R -m u:logstash:r-x /var/log/

- name: Update log rights
  file: path={{ logstash_change_log_dir }} state=directory recurse=yes mode=0755
#  owner={{ logstash_user }} group={{ logstash_group }}

- name: log | Configure change_directory_rights.sh file
  when: (ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu') and logstash_change_log_dir_enabled
  template:
    src: change_directory_rights.sh.j2
    dest: '{{ shell_dir_tmp }}/change_directory_rights.sh'
    owner: '{{ shell_owner }}'
    group: '{{ shell_group }}'
    mode: 0755
  tags: log

- name: log | Update log files rights
  action: shell '{{ shell_dir_tmp }}/change_directory_rights.sh'
  when: (ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu') and logstash_change_log_dir_enabled
  tags: log

- name: Create custom configuration file for local collectd.
  template:
    src: custom.sh.j2
    dest: '{{ collectd_prefix_custom_dir }}/custom.sh'
    owner: '{{ jenkins_owner }}'
    group: '{{ jenkins_group }}'
    mode: 0644
  when: logstash_monitor_local_collectd
#  notify: restart collectd

- name: Create configuration file for local collectd.
  template:
    src: collectd.conf.j2
    dest: '{{ collectd_prefix_conf }}/collectd.conf'
    owner: '{{ shell_owner }}'
    group: '{{ shell_group }}'
    mode: 0644
  when: logstash_monitor_local_collectd
#  notify: restart collectd

#see https://github.com/vspiewak/elk-devops-day-2014/tree/master/demo-all

- name: Copy the kibana sample
  copy:
    src: '{{ item }}'
    dest: '{{ kibana_dashboard }}/{{ item }}'
    owner: root
    group: root
    mode: 0644
  with_items:
    - nabla.json
    - collectd.json
  when: kibana_dashboard_enabled

- name: Ensure Logstash is started and enabled on boot.
  service: name=logstash state=started enabled=yes
